version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
    volumes:
      # database configuration
      - ./data:/data
      # development theme setup
      - ./dist/wp-content/themes:/app/wp-content/themes
      # development plugin setup
      - ./dist/wp-content/plugins:/app/wp-content/plugins
      # WordPress uploads folder
      - ./dist/wp-content/uploads:/app/wp-content/uploads
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        acf-field-date-time-picker,
        advanced-custom-fields,
        akismet,
        blog-copier,
        bu-navigation,
        bu-section-editing,
        calculated-fields-form,
        constant-contact-forms,
        custom-facebook-feed,
        custom-javascript-editor,
        duplicate-post,
        duracelltomi-google-tag-manager,
        easy-pricing-tables,
        easy-twitter-feed-widget,
        [local]elegant-themes-updater,
        eltdf-cpt,
        enable-media-replace,
        enhanced-media-library,
        ewww-image-optimizer,
        flipping-cards,
        font-awesome-shortcodes,
        [local]gravityforms,
        [local]gravity-forms-salesforce,
        gs-logo-slider,
        hubspot-tracking-code,
        instagram-feed,
        js_composer,
        json-api,
        json-content-importer,
        post-expirator,
        preserved-html-editor-markup-plus,
        shibboleth-username-override-only,
        soliloquy-lite,
        tablepress,
        tablepress-responsive-tables,
        the-events-calendar,
        [local]uwm-simple-301-redirects,
        [local]uwo-people,
        [local]uwo-utilities,
        wordpress-importer,
        wordpress-seo,
        wp-cerber,
        wp-private-content-plus,
        wp-simple-anchors-links,
        wp-super-cache
      THEMES: >-
        [local]Divi,
        [local]uw-oshkosh-divi
      WP_DEBUG: 'true'
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
